const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSystemInfo:     ()            => ipcRenderer.invoke('get-system-info'),
  getSettings:       ()            => ipcRenderer.invoke('get-settings'),
  setRefreshProfile: (profile)     => ipcRenderer.invoke('set-refresh-profile', profile),
  getAutoCareState:  ()            => ipcRenderer.invoke('get-auto-care-state'),
  setAutoCareSettings:(data)       => ipcRenderer.invoke('set-auto-care-settings', data),
  runAutoCareNow:    ()            => ipcRenderer.invoke('run-auto-care-now'),
  getRamProcesses:   ()            => ipcRenderer.invoke('get-ram-processes'),
  getCpuProcesses:   ()            => ipcRenderer.invoke('get-cpu-processes'),
  freeRAM:           ()            => ipcRenderer.invoke('free-ram'),
  deepCleanRAM:      (pids)        => ipcRenderer.invoke('deep-clean-ram', pids),
  quitProcess:       (pid)         => ipcRenderer.invoke('quit-process', pid),
  getDiskJunk:       ()            => ipcRenderer.invoke('get-disk-junk'),
  cleanDiskItem:     (id)          => ipcRenderer.invoke('clean-disk-item', id),
  scanDuplicates:    (options)     => ipcRenderer.invoke('scan-duplicates', options),
  trashPaths:        (paths)       => ipcRenderer.invoke('trash-paths', paths),
  getSpaceLens:      (options)     => ipcRenderer.invoke('get-space-lens', options),
  getCloudCleanupReport:(options)  => ipcRenderer.invoke('get-cloud-cleanup-report', options),
  cleanCloudProviderCache:(payload)=> ipcRenderer.invoke('clean-cloud-provider-cache', payload),
  getProtectionReport:(options)    => ipcRenderer.invoke('get-protection-report', options),
  runProtectionAction:(payload)    => ipcRenderer.invoke('run-protection-action', payload),
  getCleanupHistory:(options)      => ipcRenderer.invoke('get-cleanup-history', options),
  restoreCleanupEntry:(payload)    => ipcRenderer.invoke('restore-cleanup-entry', payload),
  clearCleanupHistory:()           => ipcRenderer.invoke('clear-cleanup-history'),
  listApps:          ()            => ipcRenderer.invoke('list-apps'),
  uninstallApp:      (data)        => ipcRenderer.invoke('uninstall-app', data),
  cleanAppLeftovers: (data)        => ipcRenderer.invoke('clean-app-leftovers', data),
  getStartupItems:   ()            => ipcRenderer.invoke('get-startup-items'),
  toggleStartupItem: (data)        => ipcRenderer.invoke('toggle-startup-item', data),
  clearPrivacy:      (itemId)      => ipcRenderer.invoke('clear-privacy', itemId),
  openActivityMonitor:()           => ipcRenderer.invoke('open-activity-monitor'),
  openInFinder:      (filePath)    => ipcRenderer.invoke('open-in-finder', filePath),
  getAppVersion:     ()            => ipcRenderer.invoke('get-app-version'),
  platform:          process.platform,
  arch:              process.arch,
});
